### ISSUE TITLE
Undeclared identifiers in SDK?

### ISSUE THREAD

**Issue by f0rr0** [zakk4223/CSVirtualCamera#2]
`_transferSession` and `_pixelBufferPool` throw undeclared identifier errors while compiling. I could be integrating the SDK wrongly though

**Comment by f0rr0** [comment]
I was able to resolve this by declaring above variables in header file. But when i made a sample app, the connection between the mach service and app never gets established. MacOS console says 'Mach lookup denied'. I am guessing this has to do something with Sanboxing. Have you experienced anything like this before? @zakk4223

**Comment by zakk4223** [comment]
I think if the app is sandboxed it needs an entitlement to lookup global mach names/XPC Services. Look into com.apple.security.temporary-exception.mach-lookup.global-name entitlement array.

I have no idea what the implications of using this entitlement are for App Store review if that's relevant to you

**Comment by f0rr0** [comment]
Thanks for this I’ll look into it! Are you available on any online forums to perhaps have a conversation around this whole repo. I’d like to buy you a beer/coffee for explaining this stuff so concisely

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Raj123456788** [comment]
@f0rr0: Can you please answer my question https://github.com/zakk4223/CSVirtualCamera/issues/3
